import * as React from "react";
import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/providers";
import { cn } from "@/lib/utils";
import { auth } from "@/lib/auth";
import { FC, PropsWithChildren } from "react";
import { Profile } from "@/components/profile";
import { Toaster } from "sonner";
import { QueryProvider } from "@/providers/query-provider";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

interface SideBarProps extends PropsWithChildren {
  className?: string;
}

const SideBar: FC<SideBarProps> = ({ children, className }) => {
  return (
    <aside>
      <div
        className={cn("hidden max-w-md px-6 pb-6 pt-12 xl:block", className)}
      >
        {children}
      </div>
    </aside>
  );
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({
  children,
}: Readonly<RootLayoutProps>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          GeistSans.className,
        )}
      >
        <QueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="max-w-2x grid min-h-screen grid-cols-[0,1fr,0] grid-rows-[64px,1fr] bg-background md:grid-cols-[1fr,672px,1fr]">
              <div className="border-b"></div>
              <div className="border-b md:border-x">
                <Navbar />
              </div>
              <div className="border-b"></div>
              <SideBar className="ml-auto">
                {session ? <Profile user={session.user} /> : null}
              </SideBar>
              <main className="md:border-x">{children}</main>
              <SideBar>FUTURE: trending topics</SideBar>
            </div>
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
